import { FieldSpec } from "./Model.js"

export const fieldDefinitions: FieldSpec[] = [
  {
    name: 'id',
    type: 'UUID',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: false
  },
  {
    name: 'action_id',
    type: 'number',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: true
  },
  {
    name: 'date_start',
    type: 'timestamp',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: true
  },
  {
    name: 'date_end',
    type: 'timestamp',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'description',
    type: 'string',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'last_sent',
    type: 'timestamp',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'number',
    type: 'string',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'pco_number',
    type: 'string',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'subject',
    type: 'string',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'subtotal_amount',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'subtotal_markup',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'total_amount',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'total_hours',
    type: 'number',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'total_paid',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'total_retainage',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'added_days',
    type: 'number',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'contract_original_total',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'contract_previous_change',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'contract_previous_total',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'change_total',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'contract_new_total',
    type: 'number',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'contract_number',
    type: 'string',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'date_contract',
    type: 'timestamp',
    requiredForCreateRequest: false,
    returnFromDbQuery: true,
    canBeModifiedByUser: true,
  },
  {
    name: 'company_id',
    type: 'UUID',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: false,
  },
  {
    name: 'project_id',
    type: 'UUID',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: false,
  },
  {
    name: 'created_by',
    type: 'UUID',
    requiredForCreateRequest: true,
    returnFromDbQuery: true,
    canBeModifiedByUser: false,
  },
  {
    name: 'date_created',
    type: 'timestamp',
    requiredForCreateRequest: false,
    returnFromDbQuery: false,
    canBeModifiedByUser: false,
  },
  {
    name: 'date_modified',
    type: 'timestamp',
    requiredForCreateRequest: false,
    returnFromDbQuery: false,
    canBeModifiedByUser: false,
  },
]
